### ISSUE TITLE
Global data?

### ISSUE THREAD

**Issue by johnmudd** [Kozea/Multicorn#101]
Postgres supports sharing data between Python functions. 
http://www.postgresql.org/docs/9.4/static/plpython-sharing.html
https://gist.github.com/rturowicz/5232050

Can something like that be available to Multicorn?

John

**Comment by rdunklau** [comment]
Hello.

In Multicorn, the data is already shared from one call to the next: one CPython interpreter is initialized per backend the first time it is needed. So, if you want to share data across multiple calls, you could either:

 - store it on the ForeignDataWrapper instance corresponding to the table: it will be available for subsequent queries on the same foreign table
 - store it on the ForeignDataWrapper class corresponding to your server: it will be available fro subsequent queries involving the same class (ie, foreign table sharing the same "wrapper" option at the server level)
 - store it anywhere else: you can declare a module containing a dictionary, or an object, and assign values to that. You don't have to care about access concurrency, since the interpreter is initialized per backend, only one process can have access to the data. From anywhere else (even in PL/Python functions), you can import this module and use it.

What you can't do is share data accross multiple backends / sessions.

I hope this answer your question, if not, feel free to ask some more.
